framework:
    cache:
         # Nom unique de votre application : utilisé pour calculer des espaces de noms stables pour les clés de cache.
        #prefix_seed: your_vendor_name/app_name

       # Le cache "app" est stocké dans le système de fichiers par défaut.
        # Les données de ce cache doivent persister entre les déploiements.
        # Les autres options incluent :

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (non recommandé avec les lourdes charges de travail d'écriture aléatoire car la fragmentation de la mémoire peut entraîner des problèmes de performances)
        #app: cache.adapter.apcu

        # Les pools avec espace de noms utilisent par défaut le backend "app" ci-dessus
        #pools:
            #my.dedicated.cache: null
