doctrine_migrations:
    migrations_paths:
        # L'espace de noms est arbitraire mais doit être différent de App\Migrations
        # car les classes de migration ne doivent PAS être chargées automatiquement
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
